apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: kiraops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: kiraops-orders:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "orders"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: kiraops
  labels:
    app: orders
spec:
  selector:
    app: orders
  ports:
    - name: http
      port: 3004
      targetPort: 3004
